spring:
  application:
    name: rozhnov

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/transfers
    username: adm
    password: adm
    driver-class-name: com.mysql.jdbc.Driver
